export const provience = [
	{ label: "Alberta", value: "Alberta" },
	{ label: "British Columbia", value: "British Columbia" },
	{ label: "Manitoba", value: "Manitoba" },
	{ label: "New Brunswick", value: "New Brunswick" },
	{ label: "Newfoundland and Labrador", value: "Newfoundland and Labrador" },
	{ label: "Nova Scotia", value: "Nova Scotia" },
	{ label: "Ontario", value: "Ontario" },
	{ label: "Prince Edward Island", value: "Prince Edward Island" },
	{ label: "Quebec", value: "Quebec" },
	{ label: "Saskatchewan", value: "Saskatchewan" },
	{ label: "Northwest Territories", value: "Northwest Territories" },
	{ label: "Nunavut", value: "Nunavut" },
	{ label: "Yukon", value: "Yukon" },
];
